name: mmperf CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Build Environment
      run: |
        SRC_DIR="$PWD"
        mkdir -p /tmp/mmperf/mmperf_venv
        cd /tmp/mmperf/mmperf_venv
        "$SRC_DIR/setup/setup-build-env-ubuntu-20.04-x86_64.sh"

    - name: Configure
      run: |
        SRC_DIR="$PWD"
        mkdir -p /tmp/mmperf/build
        cd /tmp/mmperf/build
        "$SRC_DIR/setup/configure.sh" --build-type $BUILD_TYPE

    - name: Build
      run: |
        cd /tmp/mmperf/build
        "$SRC_DIR/setup/build.sh"

    - name: Test
      run: |
        SRC_DIR="$PWD"
        cd /tmp/mmperf/build
        "$SRC_DIR/setup/test.sh"
